// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import 'vue'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ContactCard: typeof import('./src/components/ContactCard.vue')['default']
    CountdownToAllowMint: typeof import('./src/components/CountdownToAllowMint.vue')['default']
    CustomButton: typeof import('./src/components/CustomButton.vue')['default']
    CustomInput: typeof import('./src/components/CustomInput.vue')['default']
    CustomPagination: typeof import('./src/components/CustomPagination.vue')['default']
    CustomSelect: typeof import('./src/components/CustomSelect.vue')['default']
    CustomSwitch: typeof import('./src/components/CustomSwitch.vue')['default']
    EggSvg: typeof import('./src/components/svg/EggSvg.vue')['default']
    GameNotification: typeof import('./src/components/GameNotification.vue')['default']
    GameOverCounter: typeof import('./src/components/GameOverCounter.vue')['default']
    GameOverModal: typeof import('./src/components/GameOverModal.vue')['default']
    GameScreen: typeof import('./src/components/GameScreen.vue')['default']
    InteractionEntry: typeof import('./src/components/InteractionEntry.vue')['default']
    InteractionInfo: typeof import('./src/components/InteractionInfo.vue')['default']
    LabelMintStatus: typeof import('./src/components/LabelMintStatus.vue')['default']
    ListStats: typeof import('./src/components/ListStats.vue')['default']
    MainLayout: typeof import('./src/components/MainLayout.vue')['default']
    MainScreen: typeof import('./src/components/MainScreen.vue')['default']
    MintInformation: typeof import('./src/components/MintInformation.vue')['default']
    ModalBase: typeof import('./src/components/ModalBase.vue')['default']
    ModalClaimConfirmation: typeof import('./src/components/ModalClaimConfirmation.vue')['default']
    ModalDialog: typeof import('./src/components/ModalDialog.vue')['default']
    ModalExport: typeof import('./src/components/ModalExport.vue')['default']
    ModalGameOver: typeof import('./src/components/ModalGameOver.vue')['default']
    ModalMint: typeof import('./src/components/ModalMint.vue')['default']
    ModalOpenEgg: typeof import('./src/components/ModalOpenEgg.vue')['default']
    ModalShareSocials: typeof import('./src/components/ModalShareSocials.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NFTPreview: typeof import('./src/components/NFTPreview.vue')['default']
    OpenIndicator: typeof import('./src/components/svg/OpenIndicator.vue')['default']
    PlayerGlobalData: typeof import('./src/components/PlayerGlobalData.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionHeader: typeof import('./src/components/SectionHeader.vue')['default']
    SubtabButton: typeof import('./src/components/SubtabButton.vue')['default']
    SvgImage: typeof import('./src/components/SvgImage.vue')['default']
    TabButton: typeof import('./src/components/TabButton.vue')['default']
    TimeLeft: typeof import('./src/components/TimeLeft.vue')['default']
    UserName: typeof import('./src/components/UserName.vue')['default']
    WitnetStrip: typeof import('./src/components/WitnetStrip.vue')['default']
    WittyCreature: typeof import('./src/components/svg/WittyCreature.vue')['default']
  }
}

export {}
